### ISSUE TITLE
Capture Attribute not supported in 4.2

### ISSUE THREAD

**Issue by Dangry98** [BrendanParmer/NodeToPython#112]
This node gives errors becouse of the new 4.2 update:
![image](https://github.com/user-attachments/assets/66c9bde7-3b1f-4139-94a9-abfeb1f62913)

**Comment by BrendanParmer** [comment]
Hi @Dangry98, Blender 4.2 is not supported by NodeToPython yet. The capture attribute node should be supported in the `Blender-4.2` branch, but this is experimental and may not be fully stable yet. I'm expecting to release these changes in the coming weeks

**Comment by Dangry98** [comment]
Thanks! Really appreciate the work you are doing! The add-on is invaluable! Hope you consider adding it to the Blender Extension site as well :)

**Comment by BrendanParmer** [comment]
Glad to hear it's helpful! I'm planning on rolling it out to the extensions platform with the NTP 3.2 update, which will include support for creating the new manifest files, as well

**Comment by BrendanParmer** [comment]
Resolved with https://github.com/BrendanParmer/NodeToPython/pull/117
