### ISSUE TITLE
Issue with “Node to Python” Add-on in Blender 4.2 on Mac

### ISSUE THREAD

**Issue by applejamkorea** [BrendanParmer/NodeToPython#113]
Dear BrendanParmer,

I am encountering an error while installing the “Node to Python” add-on in Blender 4.2 on my Mac. The error message says: 'module' object has no attribute 'NodeEnumDefinition'
As a result, the add-on installation fails. Could you assist me with this issue?

Thank you, 
205

![1](https://github.com/user-attachments/assets/89148a70-8144-441f-a3b3-4eb03f40152c)
![2](https://github.com/user-attachments/assets/49ad2d8a-7808-4cc6-aa28-850f9f88dca0)

**Comment by BrendanParmer** [comment]
Hi @applejamkorea, Blender 4.2 is not supported by NodeToPython yet. They made some breaking changes to the Menu Switch node's API that result in this error. These should be resolved in the `Blender-4.2` branch, but this is experimental and may not be fully stable yet. I'm expecting to release these changes in the next few weeks

**Comment by BrendanParmer** [comment]
Resolved with #117
