### ISSUE TITLE
Blender4.1: Display a geometry node in the modifiers menu

### ISSUE THREAD

**Issue by Fredo38-ai** [BrendanParmer/NodeToPython#119]
I used your code to generate an addon for a geometry node. I've modified the code a little so that it can appear in the "Add" menu of the Geometry node editor as well as in the Shader Editor. I'd also like the geometry node to appear in the modifiers menu. Could you tell me how to modify your code for this? I think this would be an interesting option to develop further. Thank you very much for your help.

**Comment by BrendanParmer** [comment]
Hi @Fredo38-ai, with NodeToPython 3.1 and before you can scroll down to the `register()` and `unregister()` functions, and replace `VIEW3D_MT_object` with the menu you'd like to set it to. In your case the relevant strings would be `NODE_MT_add` or `OBJECT_MT_modifier_add`. If you have Python Tooltips enabled in your preferences, you can generally find the names of the menu you want by hovering over them. 

NodeToPython 3.2 is going to expose this Menu ID in the Options panel so you don't have to do a manual replacement. Currently you can find this in the `v3.2` branch, and I'm expecting to merge this into main fairly soon

**Comment by Fredo38-ai** [comment]
Hi Brendon Parmer,
Thank you for your quick answer.
I have already replaced the  VIEW3D_MT_object and used the NODE_MT_add function but I couldn't get my geometry node to appear in the modifiers menu.
 Here's the end of my python code, which includes the part of the script to make a menu appear in the Geometry node editor and the Shader editor:

"class ADD_MT_captureattributeangle(bpy.types.Menu):
    bl_idname = 'NODE_MT_add_captureattributeangle'
    bl_label = 'CaptureAttributeAngle'

    def draw(self, context):
        layout = self.layout
        if context.space_data.tree_type == "ShaderNodeTree" and context.space_data.shader_type == "OBJECT":
            layout.operator(ADD_OT_CaptureAttributeAngle.bl_idname, icon='SNAP_VOLUME')
        if context.space_data.tree_type == "GeometryNodeTree" and context.space_data.shader_type == "OBJECT":
            layout.operator(ADD_OT_CaptureAttributeAngle.bl_idname, icon='SNAP_VOLUME')



def captureattributeangle_menu(self, context):
    mats=1
    worlds=0
    comps=0
    geos=1
    if context.space_data.tree_type == "ShaderNodeTree" and context.space_data.shader_type == "OBJECT" and mats:
        self.layout.menu(ADD_MT_captureattributeangle.bl_idname)
    if context.space_data.tree_type == "ShaderNodeTree" and context.space_data.shader_type == "WORLD" and worlds:
        self.layout.menu(ADD_MT_captureattributeangle.bl_idname)
    if context.space_data.tree_type == "CompositorNodeTree" and comps:
        self.layout.menu(ADD_MT_captureattributeangle.bl_idname)
    if context.space_data.tree_type == "GeometryNodeTree" and context.space_data.shader_type == "OBJECT" and geos:
        self.layout.menu(ADD_MT_captureattributeangle.bl_idname)


classes=(ADD_OT_CaptureAttributeAngle, ADD_MT_captureattributeangle)            
def register():
    from bpy.utils import register_class
    for cls in classes:
        register_class(cls)
    #bpy.types.NODE_MT_editor_menus.append(menu_func)
    bpy.types.NODE_MT_add.append(captureattributeangle_menu)

            
def unregister():
    from bpy.utils import unregister_class
    for cls in classes:
        unregister_class(cls)
    #bpy.types.NODE_MT_editor_menus.remove(menu_func)
    bpy.types.NODE_MT_add.remove(captureattributeangle_menu)

            
if __name__ == "__main__":
    register()
"

 I've been looking for a while but can't figure out how to make my geometry node appear in the modifiers menu too?Can you give me a more precise indication?Thanks again for your help.Best regards.F. AITKEN



    Le samedi 10 août 2024 à 18:55:08 UTC+2, Brendan Parmer ***@***.***> a écrit :  
 
 


Hi @Fredo38-ai, with NodeToPython 3.1 and before you can scroll down to the register() and unregister() functions, and replace VIEW3D_MT_object with the menu you'd like to set it to. In your case the relevant strings would be NODE_MT_add or OBJECT_MT_modifier_add. If you have Python Tooltips enabled in your preferences, you can generally find the names of the menu you want by hovering over them.

NodeToPython 3.2 is going to expose this Menu ID in the Options panel so you don't have to do a manual replacement. Currently you can find this in the v3.2 branch, and I'm expecting to merge this into main fairly soon

**Comment by BrendanParmer** [comment]
If I understand correctly that you want to add your menu to the Add Modifier menu, I'd probably suggest something like

```python3
def add_modifier_menu_func(self, context):
    self.layout.menu(ADD_MT_captureattributeangle.bl_idname)

def register():
    from bpy.utils import register_class
    for cls in classes:
        register_class(cls)
    bpy.types.NODE_MT_add.append(captureattributeangle_menu)
    bpy.types.OBJECT_MT_modifier_add.append(add_modifier_menu_func)

            
def unregister():
    from bpy.utils import unregister_class
    for cls in classes:
        unregister_class(cls)
    bpy.types.NODE_MT_add.remove(captureattributeangle_menu)
    bpy.types.OBJECT_MT_modifier_add.remove(add_modifier_menu_func)
```

If you just want the operator for a specific node group, you could replace `add_modifier_menu_func` with
```python3
def add_modifier_menu_func(self, context):
    self.layout.operator(ADD_OT_CaptureAttributeAngle.bl_idname)
```
Let me know if this helps!

**Comment by Fredo38-ai** [comment]
Dear Brendan Parmer,
I'm sorry for my late reply but I've been out hiking for the past few days.
Thank you very much for your help as you put me on the right track and now my script is working the way I wanted it to. In fact I didn't know about the bpy.types.OBJECT_MT_modifier_add function and I've been looking for it for a while! I've learned something!
If you can integrate these different possibilities into your NodeToPython addon, I think it will be useful to others than me.
Best regards,F. AITKEN

    Le dimanche 11 août 2024 à 22:44:44 UTC+2, Brendan Parmer ***@***.***> a écrit :  
 
 


If I understand correctly that you want to add your menu to the Add Modifier menu, I'd probably suggest something like
def add_modifier_menu_func(self, context):
    self.layout.menu(ADD_MT_captureattributeangle.bl_idname)

def register():
    from bpy.utils import register_class
    for cls in classes:
        register_class(cls)
    bpy.types.NODE_MT_add.append(captureattributeangle_menu)
    bpy.types.OBJECT_MT_modifier_add.append(add_modifier_menu_func)

            
def unregister():
    from bpy.utils import unregister_class
    for cls in classes:
        unregister_class(cls)
    bpy.types.NODE_MT_add.remove(captureattributeangle_menu)
    bpy.types.OBJECT_MT_modifier_add.remove(add_modifier_menu_func)
If you just want the operator for a specific node group, you could replace add_modifier_menu_func with
def add_modifier_menu_func(self, context):
    self.layout.operator(ADD_OT_CaptureAttributeAngle.bl_idname)
Let me know if this helps!

**Comment by BrendanParmer** [comment]
Hope you've enjoyed your holiday!
