### ISSUE TITLE
Not creating links properly on nodes with multiple inputs with the same name

### ISSUE THREAD

**Issue by NaroGugul** [BrendanParmer/NodeToPython#13]
Example, an capture_attribute node have 5 inputs called 'Value', so when creating links like
`aaaaa.links.new(radius.outputs["Radius"], capture_attribute.inputs["Value"])`, and using Float, it doesnt create the link properly.
changing "Value" with 2 `aaaaa.links.new(radius.outputs["Radius"], capture_attribute.inputs[2]`), works as intended

ps. just seen this issue was closed before.

**Comment by BrendanParmer** [comment]
Thanks for letting me know about this. Latest commit should fix this and a few other issues. Let me know if this resolved your problem and I'll close the issue. If not, could you send me a test blend file and what OS and version of Blender you're using?
