### ISSUE TITLE
Can you provide a screenshot "Then, go to Object > Node to Python, and type in the name of your node group"

### ISSUE THREAD

**Issue by fluidnotions** [BrendanParmer/NodeToPython#25]
Hey Brendan,
Cool project. I'm a coder just learning blender, I would love to explore some geo node's I found online as code.
If you mean Object in the outliner panel I don't see the option there after installing your script as an addon.

**Comment by BrendanParmer** [comment]
Sure thing!

You'll want to click on an object, and in the upper right there's the object panel. It'll register at the very bottom.
![image](https://user-images.githubusercontent.com/51296046/210186886-1234c9af-8d60-4e17-ae70-e92620521558.png)
Once you click on it you'll be given a box in the lower left to type in the name of your node group.

If you prefer accessing it from the Python console, you can do so with
```
>>> bpy.ops.object.node_to_python(node_group_name = "YOUR_NODE_GROUP_NAME_HERE")
```
I don't like where I'm currently registering that button or the method of selecting a node group, so this will probably change in future releases.
