### ISSUE TITLE
Float curves seem to have double values at 0 and 1.

### ISSUE THREAD

**Issue by Talvara** [BrendanParmer/NodeToPython#41]
It looks like the initial values on a curve do not get removed when new values are added.
![blender_YeeeSKDPTv](https://user-images.githubusercontent.com/2892579/216785369-cd819fc7-b13e-41e4-b3af-6a0784c6bb25.png)
Above, How the curves are in the geometry nodes.
Below, How the curves are when using the addon created for these geometry nodes.
![blender_FE1TRLgPSR](https://user-images.githubusercontent.com/2892579/216785435-17441e7a-e02f-4141-9e11-48b96c4e860b.png)

Ran into this when trying out the plugin on this fantasy tree by RC12
https://rc12.gumroad.com/l/fantasytree

Reprosteps:

1. get the .blend file from the gumroad linked above.
2. use the 'NodeToPython' addon on the tree object in the scene.
3. Install and activate the newly created 'Fantasy tree' Addon.
4. add a cube to the scene.
5. use "bpy.ops.object.fantasy_tree()" on the cube.
6. Inspect the curves in the newly created tree and compare them to the curves of the original.

**Comment by BrendanParmer** [comment]
Same issue was occurring with color ramps, as well, thanks for the report!
