### ISSUE TITLE
Why can't the NodeSocket of the node group be automatically generated?

### ISSUE THREAD

**Issue by chenpaner** [BrendanParmer/NodeToPython#50]
**Why can't the node group automatically generate the corresponding NodeSocket after using the plug-in to export python in blender 3.5?**
![Snipaste_2023-05-23_16-09-54](https://github.com/BrendanParmer/NodeToPython/assets/107256886/67975795-0894-46a2-af9c-e57987efe2d1)

![Snipaste_2023-05-23_16-14-48](https://github.com/BrendanParmer/NodeToPython/assets/107256886/9716560e-5bcb-4d94-8949-36c189735bc8)

**Comment by BrendanParmer** [comment]
Hi @chenpaner, thanks for pointing out this bug. The latest commit should fix this, let me know if you're still having any issues

**Comment by chenpaner** [comment]
I have updated to version 2.1, but there is still this bug!

**Comment by chenpaner** [comment]
I've updated to yesterday's version 2.1, but there's this bug!

Python: Traceback (most recent call last):
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\NodeToPython\materials.py", line 212, in execute
    process_mat_node_group(nt, 2, node_vars, used_vars)
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\NodeToPython\materials.py", line 169, in process_mat_node_group
    process_mat_node_group(node_nt, level + 1, node_vars, used_vars)
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\NodeToPython\materials.py", line 192, in process_mat_node_group
    if img.source in {'FILE', 'GENERATED', 'TILED'}:
AttributeError: 'NoneType' object has no attribute 'source'

![Snipaste_2023-05-25_00-55-14](https://github.com/BrendanParmer/NodeToPython/assets/107256886/ce556783-2013-43ae-b255-41953210542b)

**Comment by BrendanParmer** [comment]
Should be fixed now, thanks for reporting! If you find any other bugs submit a new issue and I'm happy to take a look

**Comment by chenpaner** [comment]
I have tried the latest version and it works fine, thank you so much！ By the way, you wrote version 2.1.1, but in fact the plugin wrote 2.1.0!
