### ISSUE TITLE
Better instructions - Where is new nodegroup and how to apply?

### ISSUE THREAD

**Issue by powersprouter** [BrendanParmer/NodeToPython#69]
Nevermind - I figured it out. Great add-on! Thank you for this.

**Comment by BrendanParmer** [comment]
Hi @powersprouter, glad to hear you're enjoying the add-on!

This is a good question, it's not very well-documented right now. For anyone else wondering the same thing,
* In add-on mode, NodeToPython defaults to adding the generated operator to the Object Mode Object tab. It'll be at the bottom of the list
![image](https://github.com/BrendanParmer/NodeToPython/assets/51296046/ee14e90e-a38f-486a-9bf2-d617748e4b8d)

I'm not a huge fan of its current location. In a future release I'll set the default to a more appropriate spot, and I'd like to make this and the other options in the generated add-on header configurable

**Comment by powersprouter** [comment]
Thank you. I love this add-on. My python skills are not at your level yet - I'm getting better! - but I hope you enjoy my effort at addressing this issue. I intuitively could generate the script but since I didn't realize you put the Add-On in the Object menu (um, duh, like, why didn't I simply just read your code! apologies), I went ahead and first created a test case (my voronoiThis repository) and then generalize a UI wrapper that puts it in a big button in the n-panel. https://github.com/powersprouter/NodeToButtonTemplate

Instructions are in comments in the code of each .py file itself, but an obvious improvement would be to automate it all the way, sorry didn't get that far.

The method to program Blender's UI Panel and menus could be so much better, would be nice if someone took this challenge on. I have seen some instructions how to include colorful gifs as buttons but overall I would love to have more creative/artistic options. Maybe I'm not good enough at it yet. Anyway! 

Love the add-on. Am a geometry node fool right now!!

Cheerz Andrew

**Comment by powersprouter** [comment]
PS I wish there were a way to include keyframes & timeline in your conversion. Using geometry nodes in a tree of logic to do an animation is slower for me than to keyframe the nodes. Wonder if there is a way I'm missing.

**Comment by BrendanParmer** [comment]
Good stuff! Thanks for contributing to the community.

I like the idea of supporting animation stuff a little better. I'm hoping to look more into keyframing and using drivers after the 3.0 update
