### ISSUE TITLE
Saving Material as an addon error

### ISSUE THREAD

**Issue by robenSikk** [BrendanParmer/NodeToPython#87]
Hello! Thank you for your addon!
I have tried the latest version (3.0.0) In blender 4.0.1 and 4.1.0, and found some error, when exporting material as addon. Error text below:
Python: Traceback (most recent call last):
  File "C:\Users\user_name\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\NodeToPython\material\operator.py", line 174, in execute
    self._zip_addon(self._zip_dir)
TypeError: NTP_Operator._zip_addon() takes 1 positional argument but 2 were given

Exporting geometry nodes as an addon works fine.

**Comment by robenSikk** [comment]
I tried to edit material operator, and compared it to geometry nodes operator.
At the end of the code, I have deleted selected text
and it seems to be working fine now
![image](https://github.com/BrendanParmer/NodeToPython/assets/95298125/7a49896c-b4d2-4497-b456-8281a6d4323f)
only thing is I need to set saving directory, otherwise I will get an error
Python: Traceback (most recent call last):
  File "C:\Users\RobenSikk\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\NodeToPython\material\operator.py", line 142, in execute
    self._file = open(f"{self._addon_dir}/__init__.py", "w")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'None/__init__.py'
but when I set directory manually it works fine

**Comment by BrendanParmer** [comment]
Thanks for the report! The fix is now applied in v3.0.1
