### ISSUE TITLE
Blender 4.0 generated setup not behaving same as original setup despite being identical setups

### ISSUE THREAD

**Issue by hkunz** [BrendanParmer/NodeToPython#96]
I'm not sure if this is a bug in Blender 4.0 or a bug from this software. Please can you confirm? I have an original GN setup in [this file](https://blend-exchange.com/b/jl0bmOwG) which voxelizes a mesh. Notice how this works correctly with colors correctly positioned. But then when I use this tool to generate the equivalent python code and then open a new Blender 4.0 file and execute it, the new setup, despite identical to the original, does not reproduce the correct output as seen [in this blend file](https://blend-exchange.com/b/rrAaD3Md). Please can you confirm and let me know if this is a bug for the Blender development team? Or perhaps there is an incorrect python usage in the script causing this anomaly?

![image](https://github.com/BrendanParmer/NodeToPython/assets/2459196/6f6466b5-c877-4110-a05f-c14186269e5a)

It should have looked like this:

![image](https://github.com/BrendanParmer/NodeToPython/assets/2459196/414bf854-58f1-4f51-a2d4-37ca6061872b)

**Comment by hkunz** [comment]
The last "Set Material Index" gets messed up. When you try moving the materials up and down in the materials properties, the colors start jumping around which doesn't make any sense. It's probably a Blender 4.0 bug?

**Comment by hkunz** [comment]
its probably a blender bug
https://projects.blender.org/blender/blender/issues/119258 can u confirm?

**Comment by hkunz** [comment]
I have confirmed there is a bug in NodeToPython that it interchanges the noodles going into Join Geometry node causing the problem described [in this thread](https://blender.stackexchange.com/questions/314386/python-generated-geonodes-setup-not-behaving-the-same-with-the-original-geonode)

![image](https://github.com/BrendanParmer/NodeToPython/assets/2459196/1cb8d586-19c7-45f8-9411-e771051c347b)

**Comment by scurest** [comment]
Blender 4.1 just got a Python API for retrieving the order of multi-input links last week, see https://projects.blender.org/blender/blender/pulls/118987.

So I believe this will fix it, but only for Blender versions that have that new API

```diff
diff --git a/ntp_operator.py b/ntp_operator.py
index da2e642..6b8ee08 100644
--- a/ntp_operator.py
+++ b/ntp_operator.py
@@ -1104,6 +1104,9 @@ class NTP_Operator(Operator):
         if links:
             self._write(f"#initialize {nt_var} links")
 
+        if links and hasattr(links[0], 'multi_input_sort_id'):
+            links = sorted(links, key=lambda link: link.multi_input_sort_id)
+
         for link in links:
             in_node_var = self._node_vars[link.from_node]
             input_socket = link.from_socket
```

Note that links are created from the bottom up (earlier created links have lower `multi_input_sort_id`s).

**Comment by BrendanParmer** [comment]
Thanks for the report and investigation everyone, I'll incorporate the change in NTP 3.1. Blender 4.1 or higher will be required to generate the link ordering automatically. If generating a node tree in earlier versions, you'll need to reorder the links manually unfortunately
